<?php
/**
 * Created by PhpStorm.
 * User: tingfeng-key.com
 * Date: 2016/10/28
 * Time: 9:12
 */

namespace app\admin\controller;


use Illuminate\Http\Request;

class Models extends Common
{
    private static $model;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        self::$model = model('Models');
    }

    public function fieldList(){
        $req = Request();
        if(Request()->isAjax()){
            $tableNmae = $req->controller();
            try{
                $model = model($tableNmae);
            }catch (\Exception $e){
                $model = db($tableNmae);
            }
            $map = $this->_CommonMap(Request()->param());
            if(method_exists($this, '_map')){
                $map = $this->_map($map);
            }
            $pageSize = $map['pageSize'];
            unset($map['pageSize']);
            unset($map['page']);
            //echo $pageSize;
            $result = $model->where($map)->order([
                'sort' => 'asc',
                'id'=> 'asc'
            ])->paginate($pageSize);
            return $this->result($result, 1);
        }
        return $this->fetch();
    }
}