<?php
/**
 * 游戏类型
 * Created by IntelliJ IDEA.
 * User: tingfeng
 * Date: 2016/12/23
 * Time: 11:51
 */

namespace app\game\model;

class GameType extends Common
{
    private $_dbMap = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_dbMap = db('Type');
    }

    /**
     * 获取全部数据
     * @return mixed
     */
    public function getList(){
        $this->setSort();
        return $this->_dbMap->select();
    }
    private $_sortMap = null;
    /**
     * 设置排序
     * @return $this
     */
    private function setSort(){
        if(is_null($this->_sortMap)){
            $this->_dbMap->order($this->_sortMap);
        }
        return $this;
    }

}